### ISSUE TITLE
Different content in incognito mode versus PWA

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-publisher-sample#79]
Maybe a service worker caching issue?

Incognito mode (top story: "Sean Spicer resigns…"):

![screenshot_20170721-150606](https://user-images.githubusercontent.com/51244/28478435-5a614162-6e26-11e7-81e9-b65f384b2b27.png)

PWA (top story: "Report that Trump…"):

![screenshot_20170721-150555](https://user-images.githubusercontent.com/51244/28478443-60285db0-6e26-11e7-9306-7ff275de9f93.png)

Video: https://photos.app.goo.gl/SaaDxkYyePbO8jmQ2

**Comment by pbakaus** [comment]
Yes, this is indeed an issue with workbox, as investigated by @jeffposnick in https://github.com/GoogleChrome/workbox/issues/691. I now commented out the code in question, which should fix it for now. Let me know if you're still seeing the behaviour after two reloads.

**Comment by jeffposnick** [comment]
I'm not sure what you commented out, but if you try switching from `CacheFirst` to `StaleWhileRevalidate` for that feed until we've fixed the underlying bug, you'll end up with reasonable behavior.

**Comment by pbakaus** [comment]
@jeffposnick sadly I don't think so, as that would mean that a person coming back to the app a few days later will see old stuff, no? Or does staleWhileRevalidate honor the cacheExpiration?

**Comment by jeffposnick** [comment]
So even when https://github.com/GoogleChrome/workbox/pull/694 is merged they'll see old stuff on the next visit when using `CacheFirst`, because we don't have a `Date` header on the cross-origin response and therefore can't tell synchronously whether the response is fresh or not. The change in that PR will mean that the content will at least get purged in the background for the next visit.

`StaleWhileRevalidate` along with [`broadcastCacheUpdate`](https://workboxjs.org/reference-docs/latest/module-workbox-sw.Strategies.html#properties) configured to announce changes to the previously cached resource is probably the ideal configuration for this use case—you can listen for that update and then swap in the new content from the context of the page. The use of `broadcastCacheUpdate` for cross-origin resources also would be a problem, though, because it relies on checking Response headers, and I don't believe the Yahoo! API you're using whitelists the headers it needs...

**Comment by pbakaus** [comment]
I think I'll do networkFirst instead for now, to keep it fresh and only handle the offline use-case. Thanks for the pointers though, might play around with boradcastCacheUpdate!
